name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DEFAULT_PYTHON: 3.8

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    outputs:
      requirements: ${{ steps.requirements.outputs.exist }}
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2

      - name: Lint with JQ
        uses: home-assistant/actions/helpers/jq@master

      - name: Check integration files
        id: integrations
        run: |
          for component in components/*; do
            manifestlink=$(jq --raw-output ".manifest" "${component}")

            echo "Process: ${component} -> ${manifestlink}"
            manifest=$(curl -sSL -f "${manifestlink}" | jq -e --raw-output .)
            if [[ "$?" != 0 ]]; then
              echo "Unable to read the manifest file at ${manifestlink}"
              echo "The URL might be wrong or is not a raw URL."
              exit 1
            fi

            echo "${manifest}" | jq -e --raw-output '.requirements[0]'
            if [[ "$?" != 0 ]]; then
              echo "The integration in $component, does not seem to have any Python requirements."
              echo "Adding it to this repository has no use, since there are nothing to build for it."
              exit 1
            fi
            
            for requirement in $(echo "${manifest}" | jq -e --raw-output '.requirements[]'); do
              echo -e "\t- $requirement"
            done
          done
        
  requirements:
    needs: lint
    runs-on: ubuntu-latest
    name: Validate Python requirements
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2.2.1
        id: python
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipdeptree stdlib-list
      - name: Validate requirements
        run: |
          cat ${HOME}/files.json | jq -r '.[]' | scripts/validate_requirements.py
